### ISSUE TITLE
Travis CI build failed

### ISSUE THREAD

**Issue by fukamachi** [snmsts/roswell#25]
`ros -v run -- --version` has failed on Travis CI.

https://travis-ci.org/snmsts/roswell/jobs/48671311

I could reproduce on my Mac with the following errors.

```
ros(64717,0x7fff74f03300) malloc: *** error for object 0x10b647734: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

The output of `ros config` is here:

```
$ ros config
oneshot:
local:
ccl-bin.version=1.10[unknown]
sbcl.version=1.2.6[unknown]
sbcl-bin.version=1.1.8[unknown]
default.lisp=ccl-bin[unknown]
```

**Comment by syohex** [comment]
https://github.com/snmsts/roswell/blob/master/src/cmd-run-ccl.c#L44

Arguments of `s_cat` must be malloced memory. Because they are freed in
`s_cat2`. But SLASH is not malloced memory, it is statically allocated memory.

This is backtrace of GDB.
```
(gdb) bt
#0  0x00007ffff782e96c in __GI___libc_free (mem=0x40b63a) at malloc.c:2945
#1  0x000000000040345c in dealloc (f=0x40b63a) at util.c:32
#2  s_cat2 (a=0x6150a0 "", b=0x40b63a "/") at util.c:69
#3  0x00000000004034e5 in s_cat (first=<optimized out>) at util.c:81
#4  0x0000000000408094 in cmd_run_ccl (argc=-139028640, argc@entry=2, argv=0x7fffffffe0b0, cmd=0x0) at cmd-run-ccl.c:44
#5  0x0000000000406c68 in cmd_run_star (argc=2, argv=0x7fffffffe0b0, cmd=<optimized out>) at cmd-run.c:215
#6  0x000000000040212f in proccmd (argc=argc@entry=2, argv=argv@entry=0x7fffffffe0b0, option=<optimized out>, command=0) at lsp.c:64
#7  0x0000000000406616 in cmd_run (argc=3, argv=0x7fffffffe0a8, cmd=0x612260) at cmd-run.c:44
#8  0x0000000000402310 in proccmd (argc=argc@entry=3, argv=argv@entry=0x7fffffffe0a8, option=<optimized out>, command=<optimized out>) at lsp.c:135
#9  0x000000000040180e in main (argc=5, argv=0x7fffffffe098) at lsp.c:314
```

**Comment by snmsts** [comment]
Thank you very much.
